# Generated by Django 4.0.5 on 2022-06-21 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('submitted_by', models.ManyToManyField(blank=True, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='Qustion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustion', models.CharField(blank=True, max_length=256, null=True, verbose_name='qustion')),
                ('answer', models.CharField(blank=True, max_length=256, null=True, verbose_name='answer')),
                ('option_a', models.CharField(blank=True, max_length=256, null=True, verbose_name='a')),
                ('option_b', models.CharField(blank=True, max_length=256, null=True, verbose_name='b')),
                ('option_c', models.CharField(blank=True, max_length=256, null=True, verbose_name='c')),
                ('option_d', models.CharField(blank=True, max_length=256, null=True, verbose_name='d')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='quiz.exam')),
            ],
            options={
                'db_table': 'qustion',
            },
        ),
    ]
