# Generated by Django 4.0.5 on 2022-06-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qustion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='qustion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='qustion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='qustion',
            name='option_d',
        ),
        migrations.AlterField(
            model_name='qustion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qustions', to='quiz.exam'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(blank=True, max_length=256, null=True, verbose_name='a')),
                ('qustion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='quiz.exam')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
