# Generated by Django 4.0.5 on 2022-06-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_answer_option_alter_answer_qustion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qustion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='qustion',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='qustion',
            new_name='question',
        ),
    ]
